import type { ComponentProps } from "react";
import { getBrand } from "@tge/branding";
import type { Agent, Article, City, Developer, Locale, Property } from "@tge/types";
import { localize } from "@tge/utils";
import { absoluteUrl, localizedUrl } from "@/lib/seo";
import { Link, getPathname } from "@/i18n/navigation";

type LinkHref = ComponentProps<typeof Link>["href"];

export type JsonLdSchema = Record<string, unknown>;

const SOCIAL_LINKS = [
  "https://instagram.com/reveria",
  "https://facebook.com/reveria",
  "https://linkedin.com/company/reveria",
  "https://youtube.com/@reveria",
];

const ORG_ID = `${absoluteUrl("/")}#organization`;
const WEBSITE_ID = `${absoluteUrl("/")}#website`;

export function organizationSchema(): JsonLdSchema {
  const brand = getBrand();
  return {
    "@context": "https://schema.org",
    "@type": "Organization",
    "@id": ORG_ID,
    name: brand.name,
    url: absoluteUrl("/"),
    // /apple-icon is the convention-based PNG generated by apple-icon.tsx —
    // 180×180, always resolves, no extra asset file needed. Replace with a
    // hand-authored /logo.png when one lands in public/.
    logo: absoluteUrl("/apple-icon"),
    slogan: brand.tagline,
    sameAs: SOCIAL_LINKS,
  };
}

export function websiteSchema(locale: Locale): JsonLdSchema {
  const brand = getBrand();
  return {
    "@context": "https://schema.org",
    "@type": "WebSite",
    "@id": WEBSITE_ID,
    url: absoluteUrl("/"),
    name: brand.name,
    description: brand.tagline,
    inLanguage: locale,
    publisher: { "@id": ORG_ID },
    potentialAction: {
      "@type": "SearchAction",
      target: {
        "@type": "EntryPoint",
        urlTemplate: `${localizedUrl("/properties", locale)}?q={search_term_string}`,
      },
      "query-input": "required name=search_term_string",
    },
  };
}

export interface BreadcrumbSchemaItem {
  label: string;
  href?: LinkHref;
}

function resolveHref(href: LinkHref, locale: Locale): string {
  // getPathname returns the locale-prefixed, pathnames-mapped URL
  // ("/en/about"); we prepend the site origin to produce an absolute URL for
  // schema.org / og:url usage. The `as never` bypasses a spurious Href-union
  // mismatch when href is one of the many per-pathname object shapes.
  return absoluteUrl(getPathname({ href: href as never, locale }));
}

export function breadcrumbListSchema(
  items: BreadcrumbSchemaItem[],
  locale: Locale,
): JsonLdSchema {
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: items.map((item, index) => ({
      "@type": "ListItem",
      position: index + 1,
      name: item.label,
      ...(item.href ? { item: resolveHref(item.href, locale) } : {}),
    })),
  };
}

const AVAILABILITY: Record<Property["status"], string> = {
  available: "https://schema.org/InStock",
  reserved: "https://schema.org/LimitedAvailability",
  sold: "https://schema.org/SoldOut",
};

export function realEstateListingSchema(
  property: Property,
  locale: Locale,
): JsonLdSchema {
  const url = localizedUrl(`/properties/${property.slug}`, locale);
  const heroImage =
    property.images.find((img) => img.isHero) ?? property.images[0];
  return {
    "@context": "https://schema.org",
    "@type": ["Product", "Accommodation"],
    name: localize(property.title, locale),
    description: localize(property.description, locale),
    ...(heroImage ? { image: heroImage.src } : {}),
    url,
    sku: property.id,
    category: property.type,
    numberOfRooms: property.specs.bedrooms,
    floorSize: {
      "@type": "QuantitativeValue",
      value: property.specs.area,
      unitCode: "MTK",
    },
    address: {
      "@type": "PostalAddress",
      streetAddress: localize(property.location.address, locale),
      addressLocality: property.location.city,
      addressCountry: "RO",
    },
    geo: {
      "@type": "GeoCoordinates",
      latitude: property.location.coordinates.lat,
      longitude: property.location.coordinates.lng,
    },
    offers: {
      "@type": "Offer",
      price: property.price,
      priceCurrency: property.currency,
      availability: AVAILABILITY[property.status],
      url,
    },
    ...(property.developerName ? { brand: { "@type": "Brand", name: property.developerName } } : {}),
  };
}

export function articleSchema(article: Article, locale: Locale): JsonLdSchema {
  const url = localizedUrl(`/blog/${article.slug}`, locale);
  return {
    "@context": "https://schema.org",
    "@type": "Article",
    headline: localize(article.title, locale),
    description: localize(article.excerpt, locale),
    image: article.coverImage,
    datePublished: article.publishedAt,
    inLanguage: locale,
    author: {
      "@type": "Person",
      name: article.authorName,
    },
    publisher: { "@id": ORG_ID },
    mainEntityOfPage: { "@type": "WebPage", "@id": url },
    url,
  };
}

export function personSchema(agent: Agent, locale: Locale): JsonLdSchema {
  const name = `${agent.firstName} ${agent.lastName}`;
  return {
    "@context": "https://schema.org",
    "@type": "Person",
    name,
    jobTitle: "Real Estate Agent",
    email: agent.email,
    telephone: agent.phone,
    ...(agent.photo ? { image: agent.photo } : {}),
    description: localize(agent.bio, locale),
    url: localizedUrl(`/agents/${agent.slug}`, locale),
    worksFor: { "@id": ORG_ID },
  };
}

export function localBusinessSchema(
  developer: Developer,
  locale: Locale,
): JsonLdSchema {
  return {
    "@context": "https://schema.org",
    "@type": "RealEstateAgent",
    name: developer.name,
    description: localize(developer.description, locale),
    image: developer.coverImage ?? developer.logo,
    logo: developer.logo,
    url: localizedUrl(`/developers/${developer.slug}`, locale),
    ...(developer.website ? { sameAs: [developer.website] } : {}),
    address: {
      "@type": "PostalAddress",
      addressLocality: developer.city,
      addressCountry: "RO",
    },
  };
}

export function placeSchema(city: City, locale: Locale): JsonLdSchema {
  return {
    "@context": "https://schema.org",
    "@type": "Place",
    name: city.name,
    description: localize(city.description, locale),
    image: city.image,
    url: localizedUrl(`/cities/${city.slug}`, locale),
    ...(city.latitude != null && city.longitude != null
      ? {
          geo: {
            "@type": "GeoCoordinates",
            latitude: city.latitude,
            longitude: city.longitude,
          },
        }
      : {}),
  };
}

export interface FaqPair {
  question: string;
  answer: string;
}

export function faqPageSchema(items: FaqPair[]): JsonLdSchema {
  return {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: items.map((item) => ({
      "@type": "Question",
      name: item.question,
      acceptedAnswer: {
        "@type": "Answer",
        text: item.answer,
      },
    })),
  };
}
